[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api-n8n/*"
  to = "https://bretudev.app.n8n.cloud/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200